USB_VID = 0x239A
USB_PID = 0x805A
USB_PRODUCT = "Hackaday Supercon Badge"
USB_MANUFACTURER = "Hackaday"
USB_DEVICES = "CDC,MSC"

INTERNAL_FLASH_FILESYSTEM = 1
# EXTERNAL_FLASH_DEVICE_COUNT = 1
# EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ
